\i ./sql/create_auto_sequence.sql
\i ./sql/create_users.sql
\i ./sql/create_roles.sql
\i ./sql/create_user_roles.sql
\i ./sql/create_chat_message.sql
\i ./sql/create_message_reply_link.sql
\i ./sql/create_images.sql
\i ./sql/create_memes.sql
\i ./sql/create_message_meme_link.sql
\i ./sql/create_user_avatar_link.sql