app:
    jwtSecret: 123456
    jwtExpirationMinutes: 60
    messageDelayMs: 500
    messageAlterTimeMinutes: 1
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 123
    jpa:
        # show-sql: true
        properties:
            hibernate:
                # jdbc.lob.non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: none
                # format_sql: true
    mvc:
           log-request-details: true

logging:
    file.path: /var/log/webchat
    level:
        org.hibernate.SQL: error
        org.hibernate.type.descriptor.sql: error
        org.springframework.web: DEBUG
